import '../src/app/globals.css'
import { SessionProvider } from "next-auth/react";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function App({ Component, pageProps: { session, ...pageProps } }) {
    return (
        <SessionProvider session={session}>
            <Component {...pageProps} />
        </SessionProvider>
    );
}