import { getSession, useSession } from "next-auth/react";
import Home from "@/app/homei/page";

export const metadata = {
    title: 'home.js',
    description: 'Generated by Next.js',
}

export async function getServerSideProps(context) {
    const session = await getSession(context);
    return {
        props: { session },
    };
}


export default function index() {

    const { data: session, status } = useSession();

    return (
        <>
            <Home
                session={session}
                status={status}
            />
        </>
    )
}